# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_is_done',
            field=models.BooleanField(default=False),
        ),
    ]
